events {}

http {
    server{
        listen 80;

        # Secrity headers
        add_header X-Content-Type-Options "nosniff"       always; # Prevent browsers from guessing file type
        add_header X-Frame-Options        "DENY"          always; # Block the page from being loaded inside an iframe
        add_header X-XSS-Protection       "1; mode=block" always; # Enable build-in XSS filter for older browsers
        add_header Referrer-Policy        "no-referrer"   always; # Send no referrer header when leaving the site to prevent leaking URLs to third-parties
        server_tokens off; # hides nginx version number from response header

        location / {
            proxy_pass         http://app:3000;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        # Health check endpoint, access_log off to avoid polluting logs with ping noise
        location /health {
            proxy_pass         http://app:3000;
            access_log         off;
        }
    }
}
